config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, :path => '',
                      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :lists, except: :index do
    resources :tasks, except: [:index, :new, :edit] do
      member do
        patch :complete
        patch :prioritize
      end
    end
  end

  scope 'task/:task_id', as: :task do
    resources :comments, only: [:create, :destroy]
  end

  root        'lists#index'

  get '*path' => redirect('/')

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :comments, through: :task

  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists if current_user
  end

  def show
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json
    end
  end

  def new
    @list = current_user.lists.build
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path }
        format.js
        format.json { render :show, status: :created, location: @list }
      else
        format.html { redirect_to root_path, alert: 'Invalid list.' }
        format.js
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_path }
        format.js
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { redirect_to root_path, alert: 'Invalid list.' }
        format.js
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Confirms the correct user.
    def correct_user
      @list = current_user.lists.find_by(id: params[:id])
      redirect_to root_path if cannot? :manage, @list
    end

    def list_params
      params.require(:list).permit(:title)
    end
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %><br>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/_list.html.erb
<div id="list-<%= list.id %>" class="panel panel-primary">
  <div class="panel-heading" data-toggle="collapse" data-target="#list-<%= list.id %>-todos">
    <div class="row">
      <div class="col-md-12">
        <div class="pull-left">
          <strong>
            <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> 
            <%= list.title %>  
          </strong>          
        </div>         
        <div class="pull-right">
          <%= link_to edit_list_path(list), remote: true, 'data-toggle': "modal", 'data-target': '#modal-window', title: "Edit" do %>
            <span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %> |
          <%= link_to list, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          <% end %>                
        </div> 
      </div>        
    </div>
  </div>
  <div id="list-<%= list.id %>-todos" class="panel-collapse collapse in">
    <div class="panel-body">
      <%= render 'tasks/form', list: list, task: Task.new %>
    </div>
    <table class="table table-curved">
      <tbody>
        <% if list.tasks.any? %>
          <%= render list.tasks %>
        <% else %>
          <tr class="text-center">
            <td>
              <h4><small>No TODOS for now.</small> </h4>         
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>        
</div>

app/views/lists/_modal.html.erb
<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" title="Close" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title">
        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
        <%= modal_title %>
      </h4>
    </div>
    <div class="modal-body">
      <%= form_for list, remote: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>    
        <%= f.text_field :title, placeholder: "List title here..", autofocus: true, class: 'form-control' %>
        <div class="text-right">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/create.js.erb
<% if @list.errors.any? %>
	$("#modal-window").html("<%= escape_javascript(render 'lists/modal', list: @list, modal_title: 'Add TODO List') %>");
<% else %>
	$("div#modal-window").modal('hide');
	$("div#lists").prepend("<%= escape_javascript( render @list )%>");
<% end %>

app/views/lists/destroy.js.erb
$("div#list-<%= @list.id %>").remove();

app/views/lists/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'lists/modal', list: @list, modal_title: 'Edit List Title') %>");

app/views/lists/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="center text-uppercase">
      <h2>
        <strong>Simple todo lists</strong><br/>
        <small>From Volodymyr Shvydkyi</small>
      </h2>
    </div>

    <br/>

    <div id="lists" class="col-md-10 col-md-offset-1">
      <%= render @lists %>
    </div>

    <div class="center">
      <%= link_to new_list_path, remote: true, class: 'btn btn-primary', 'data-toggle': "modal", 'data-target': '#modal-window' do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <strong>Add TODO List</strong>
      <% end %>
    </div>

    <div id="modal-window" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Task Manager App</h1> 
    <h2><small>Created by Volodymyr Shvydkyi</small></h2>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/lists/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'lists/modal', list: @list, modal_title: 'Add TODO List') %>");

app/views/lists/update.js.erb
<% if @list.errors.any? %>
	$("#modal-window").html("<%= escape_javascript(render 'lists/modal', list: @list, modal_title: 'Edit List Title') %>");
<% else %>
	$("div#modal-window").modal('hide');
	$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");
<% end %>