config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, :path => '',
                      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :lists, except: :index do
    resources :tasks, except: [:index, :new, :edit] do
      member do
        patch :complete
        patch :prioritize
      end
    end
  end

  scope 'task/:task_id', as: :task do
    resources :comments, only: [:create, :destroy]
  end

  root        'lists#index'

  get '*path' => redirect('/')

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :task

  mount_uploader :file, FileUploader

  has_one :list, through: :task

  validates :user_id, presence: true
  validates :task_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  validate :file_size

  private

    # Validates the size of an uploaded file.
    def file_size
      if file.size > 1.megabytes
        errors.add(:file, "should be less than 1MB")
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_comment, except: [:create]

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { redirect_to root_path, alert: 'Invalid comment.' }
        format.js
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Comment was successfully destroyed.' }
      format.js
    end
  end

  private
    def correct_user
      @task = current_user.tasks.find_by(id: params[:task_id])
      redirect_to root_path if cannot? :manage, @task
    end

    def set_comment
      @comment = @task.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :file)
    end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <span class="comment-author"><%= comment.user.name %></span> 
  <span class="comment-time"><%= time_ago_in_words(comment.created_at) %></span> 
  <span>
  	<%= link_to	"×", task_comment_path(comment.task, comment), remote: true, method: :delete, class: "close", title: "Delete" %>
  </span>
  <div class="comment-text"><%= comment.content %></div>
  <% if comment.file? %>
		<% if Rails.env.production? %>
			<b>File:</b> <%= link_to comment.file.public_id, comment.file.url %>
		<% else %>
			<b>File:</b> <%= link_to comment.file.filename, comment.file.url %>
		<% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([task, comment], html: { multipart: true }, 
															remote: true, 
															authenticity_token: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="input-group">
    <%= f.text_field :content, placeholder: "Start typing here to create a comment..", class: 'form-control' %>
    <span class="input-group-btn">
      <%= button_tag "Add Comment", type: "submit", class: 'btn btn-primary' %>
    </span>
  </div>
  <%= f.file_field :file, title: "Choose a file.." %>
  <script type="text/javascript">
	  $('#comment_file').bind('change', function() {
	    var size_in_megabytes = this.files[0].size/1024/1024;
	    if (size_in_megabytes > 1) {
	      alert('Maximum file size is 1MB. Please choose a smaller file.');
	    }
	  });

	  $('#comment_file').bootstrapFileInput();

	  $('#new_comment').on('submit', function(e){
        $(this).find("button").prop( "disabled", true );
        $(this).find("button").html('Please wait..');
    });
	</script>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
	$("#new_comment").replaceWith("<%= escape_javascript( render 'comments/form', task: @comment.task, comment: @comment )%>");
<% else %>
	$("#new_comment").replaceWith("<%= escape_javascript( render 'comments/form', task: @comment.task, comment: Comment.new )%>");
	$(".comments").append("<%= escape_javascript( render @comment ) %>");
<% end %>

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();