config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, :path => '',
                      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :lists, except: :index do
    resources :tasks, except: [:index, :new, :edit] do
      member do
        patch :complete
        patch :prioritize
      end
    end
  end

  scope 'task/:task_id', as: :task do
    resources :comments, only: [:create, :destroy]
  end

  root        'lists#index'

  get '*path' => redirect('/')

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :list

  has_many :comments, dependent: :destroy

  if Rails.env.production? # Sort order for Postgres
    default_scope -> { order(completed_at: :desc, priority: :desc, created_at: :desc ) }
  else                    # Sort order for SQLite
    default_scope -> { order(:completed_at, priority: :desc, created_at: :desc ) }
  end  

  validates :user_id, presence: true
  validates :list_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  attr_reader :deadline_at

  enum priority: [:normal, :important]

  # Overriding default accessor to show local time in views
  def deadline_at
    super.localtime unless super.blank?
  end

  def completed?
    !completed_at.blank?
  end

  def has_deadline?
    !deadline_at.blank?
  end

  def failed_deadline?
    if has_deadline?
      deadline_at < Time.zone.now
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_task, except: [:create]

  def show
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @task = @list.tasks.build(task_params)
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.js
      else
        format.html { redirect_to root_path, alert: 'Invalid task.' }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.js
      else
        format.html { redirect_to root_path, alert: 'Invalid task.' }
        format.js
      end
    end
  end

  def complete
    @task.update_attribute(:completed_at, @task.completed? ? nil : Time.now)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def prioritize
    @task.important? ? @task.normal! : @task.important!
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.js
    end
  end

  private
    def correct_user
      @list = current_user.lists.find_by(id: params[:list_id])
      redirect_to root_path if cannot? :manage, @list
    end

    def set_task
      @task = @list.tasks.find(params[:id])
    end

    def task_params
      valid_params = params.require(:task).permit(:content, :completed_at, :deadline_at, :priority)

      unless valid_params[:deadline_at].blank?
        date_format = "%Y-%m-%d %I:%M %p"
        offset = DateTime.now.strftime("%z")
        valid_params[:deadline_at] = DateTime.strptime(valid_params[:deadline_at], date_format).change(offset: offset).to_s
      end

      return valid_params
    end
end

app/views/tasks/_form.html.erb
<%= form_for([list, task], remote: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="input-group">
	  <%= f.text_field :content, placeholder: "Start typing here to create a task..", class: 'form-control' %>
	  <span class="input-group-btn">
	    <%= button_tag "Add Task", type: "submit", class: 'btn btn-primary' %>
	  </span>
	</div>
<% end %>

app/views/tasks/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title">
        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
        <%= modal_title %>
      </h4>
    </div>
    <div class="modal-body">
      <%= form_for([task.list, task], remote: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>    
        <%= f.text_field :content, placeholder: "Start typing here..", autofocus: true, class: 'form-control' %>
        <div class="text-right">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_show_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true" title="Close">×</button>
      <h4 class="modal-title">
        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
        <%= modal_title %>
      </h4>
    </div>
    
    <div class="modal-body">
      <%= form_for([task.list, task], remote: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="input-group">
          <span class="input-group-addon">
              <%= f.check_box :completed_at, { class: 'group-checkbox', checked: task.completed? }, Time.zone.now, "" %>
          </span>
          <%= f.text_field :content, placeholder: "Start typing here..", autofocus: true, class: 'form-control' %>
        </div>
        <br/>
        <!-- DatTime Picker -->
        <div class="form-group">
          <%= f.label :deadline_at %>
          <div class='input-group date' id='datetimepicker1'>
            <%= f.text_field :deadline_at, placeholder: "Set deadline here..", class: "form-control" %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                  format: "YYYY-MM-DD h:mm A"
                });
            });
        </script>
        <!-- End Datetime Picker -->
        <label>Priority</label>
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <%= f.label :priority, 'Normal', class: "btn btn-default #{'active' if task.normal?}" do %>
            <%= f.radio_button :priority, :normal, checked: task.normal? %>
            Normal
          <% end %>
          <%= f.label :priority, 'Important', class: "btn btn-default #{'active' if task.important?}" do %>
            <%= f.radio_button :priority, :important, checked: task.important? %>
            <span class="star glyphicon glyphicon glyphicon-star" aria-hidden="true"></span> 
             Important
          <% end %>
        </div>
        <br/>
        <div class="pull-right">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Update", class: 'btn btn-primary' %>
        </div>
      <% end %>
      <br/>
      <div class="comments">
        <h4 class="text-center">
          Comments
        </h4>
        <%= render 'comments/form', task: task, comment: Comment.new %>
        <%= render task.comments %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<% if task.completed? %>
	<tr id="todo-item-<%= task.id %>">
		<td class="col-md-1 col-xs-1 text-center vert-align">
			<%= link_to complete_list_task_path(task.list, task), remote: true, method: :patch do %>
				<span class="glyphicon glyphicon-check" aria-hidden="true"></span>
			<% end %>
		</td>
		<td class="col-md-9 col-xs-9">
			<s><%= task.content %></s>
		</td>
		<td class="col-md-2 col-xs-2 text-center vert-align">
			<div class="hoverable">
				<%= link_to prioritize_list_task_path(task.list, task), remote: true, method: :patch, title: "Prioritize" do %>
					<span class="glyphicon glyphicon glyphicon-star-empty" aria-hidden="true"></span>
				<% end %> | 
				<%= link_to list_task_path(task.list, task), remote: true, 'data-toggle': "modal", 'data-target': '#modal-window', title: "Edit" do %>
					<span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
				<% end %> | 
				<%= link_to list_task_path(task.list, task), remote: true, method: :delete, title: "Delete" do %>
					<span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span>
				<% end %>
			</div>
		</td>
	</tr>
<% else %>
	<tr id="todo-item-<%= task.id %>">
		<td class="col-md-1 col-xs-1 text-center vert-align">
			<%= link_to complete_list_task_path(task.list, task), remote: true, method: :patch do %>
				<span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>
			<% end %>
		</td>
		<td class="col-md-9 col-xs-9">
			<% if task.important? %>
				<span class="star glyphicon glyphicon glyphicon-star" aria-hidden="true"></span>
			<% end %>			 
			<%= task.content %>
		</td>
		<td class="col-md-2 col-xs-2 text-center vert-align">
			<div class="hoverable">
				<%= link_to prioritize_list_task_path(task.list, task), remote: true, method: :patch, title: "Prioritize" do %>
					<span class="glyphicon glyphicon glyphicon-star-empty" aria-hidden="true"></span>
				<% end %> | 
				<%= link_to list_task_path(task.list, task), remote: true, 'data-toggle': "modal", 'data-target': '#modal-window', title: "Edit" do %>
					<span class="glyphicon glyphicon glyphicon-pencil" aria-hidden="true"></span>
				<% end %> | 
				<%= link_to list_task_path(task.list, task), remote: true, method: :delete, title: "Delete" do %>
					<span class="glyphicon glyphicon glyphicon-trash" aria-hidden="true"></span>
				<% end %>
			</div>
			<div class="visible visible-sm visible-md visible-lg">
				<% if task.has_deadline? %>
					<% if task.failed_deadline? %>
						<div class="task-failed-deadline">
					<% else %>
						<div class="task-deadline">
					<% end %>					
						<small>
							<span class="glyphicon glyphicon glyphicon-time" aria-hidden="true"></span> 
							<%= task.deadline_at.to_date %>
						</small>	 	
					</div>
				<% end %>
			</div>
			<div class="visible visible-xs">
				<% if task.has_deadline? %>
					<% if task.failed_deadline? %>
						<div class="task-failed-deadline">
					<% else %>
						<div class="task-deadline">
					<% end %>	
						<span class="glyphicon glyphicon glyphicon-time" aria-hidden="true"></span>	
					</div>
				<% end %>
			</div>		
		</td>
	</tr>	
<% end %>

app/views/tasks/complete.js.erb
$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");

app/views/tasks/create.js.erb
<% if @task.errors.any? %>
	$("#list-<%= @list.id %> .panel-body").html("<%= escape_javascript( render 'tasks/form', list: @list, task: @task )%>");
<% else %>
	$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");
<% end %>

app/views/tasks/destroy.js.erb
<% if @list.tasks.any? %>
	$("#todo-item-<%= @task.id %>").remove();
<% else %>
	$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");
<% end %>

app/views/tasks/prioritize.js.erb
$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");

app/views/tasks/show.js.erb
$("#modal-window").html("<%= escape_javascript(render 'tasks/show_modal', task: @task, modal_title: @task.list.title) %>");

app/views/tasks/update.js.erb
<% if @task.errors.any? %>
	$("#modal-window").html("<%= escape_javascript(render 'tasks/show_modal', task: @task, modal_title: 'Edit Task') %>");
<% else %>
	$("div#modal-window").modal('hide');
	$("div#list-<%= @list.id %>").replaceWith("<%= escape_javascript( render @list )%>");
<% end %>